#!/usr/bin/env bash
# CyanLink remote relay one-shot install script (public static script; pure install, no callbacks)
#
# Usage (args generated by the CyanLink "Install / Retry" drawer, one-line copy):
#   curl -fsSL <script-url> | bash -s -- \
#     --bind-port <frps-port> --frps-token <frp-auth-token> \
#     [--frp-dl-base <frp-mirror-base>] [--frp-version <version>]
#
# Notes: the script only installs frps and starts it; install success is judged
#        by CyanLink actively probing the control port (bind_port). Make sure
#        the security group / firewall allows bind_port.
# Privilege: requires root; auto-escalates via sudo when run as non-root.
# Warn: one relay instance per server (fixed /etc/cyanlink/frps.toml and
#       cyanlink-relay unit); re-running with new args = config reinstall,
#       the service is restarted automatically.
# All output is English on purpose: script output lands in CyanLink's raw log
# view and must not require i18n.
set -euo pipefail

BIND_PORT="" FRPS_TOKEN=""
FRP_VERSION="${FRP_VERSION:-0.61.2}"
FRP_DL_BASE="${FRP_DL_BASE:-https://github.com/fatedier/frp/releases/download}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bind-port) BIND_PORT="$2"; shift 2 ;;
    --frps-token) FRPS_TOKEN="$2"; shift 2 ;;
    --frp-dl-base) FRP_DL_BASE="$2"; shift 2 ;;
    --frp-version) FRP_VERSION="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$BIND_PORT" && -n "$FRPS_TOKEN" ]] || {
  echo "Missing --bind-port / --frps-token" >&2; exit 1;
}

# Non-root: run all privileged operations via sudo (no self re-exec in curl|bash)
SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || { echo "Error: root or sudo privilege required" >&2; exit 1; }
  SUDO="sudo"
  echo "==> Non-root user detected, privileged operations will use sudo"
fi

echo "==> CyanLink relay install (bindPort=${BIND_PORT})"

ARCH=$(uname -m)
case "$ARCH" in
  x86_64) FRP_ARCH="amd64" ;;
  aarch64 | arm64) FRP_ARCH="arm64" ;;
  *) echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

if ! command -v frps >/dev/null 2>&1; then
  echo "==> Downloading frp v${FRP_VERSION} (linux-${FRP_ARCH})"
  # Retry transient failures (flaky links truncating large downloads, curl 18 etc.)
  download() { curl -fsSL --retry 3 --retry-all-errors --connect-timeout 15 "$1" -o "$2"; }
  TGZ="$(mktemp /tmp/frp.XXXXXX.tar.gz)"
  download "${FRP_DL_BASE}/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz" "$TGZ" \
    || download "https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz" "$TGZ" \
    || { echo "Error: failed to download frp v${FRP_VERSION} from all sources" >&2; exit 1; }
  # The binary must be extracted to disk before install: command substitution would
  # blow ARG_MAX for >128KB payloads ("Argument list too long") and bash strips
  # NUL bytes, corrupting the binary.
  EXTRACT_DIR="$(mktemp -d)"
  tar -xzf "$TGZ" -C "$EXTRACT_DIR" "frp_${FRP_VERSION}_linux_${FRP_ARCH}/frps"
  $SUDO install -m 0755 "$EXTRACT_DIR/frp_${FRP_VERSION}_linux_${FRP_ARCH}/frps" /usr/local/bin/frps
  rm -rf "$EXTRACT_DIR" "$TGZ"
fi

echo "==> Writing /etc/cyanlink/frps.toml"
$SUDO mkdir -p /etc/cyanlink
$SUDO tee /etc/cyanlink/frps.toml >/dev/null <<CFG
bindAddr = "0.0.0.0"
bindPort = ${BIND_PORT}
auth.token = "${FRPS_TOKEN}"
CFG

echo "==> Registering systemd service cyanlink-relay"
$SUDO tee /etc/systemd/system/cyanlink-relay.service >/dev/null <<UNIT
[Unit]
Description=CyanLink relay (frps)
After=network-online.target

[Service]
ExecStart=/usr/local/bin/frps -c /etc/cyanlink/frps.toml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT
$SUDO systemctl daemon-reload
$SUDO systemctl enable cyanlink-relay >/dev/null
# Idempotent reinstall: `enable --now` never restarts a running unit,
# so an explicit restart is required for config changes to take effect.
$SUDO systemctl restart cyanlink-relay

echo "==> Done: frps is running. Allow TCP ${BIND_PORT} in your security group / firewall,"
echo "    the instance will show online once the CyanLink probe passes."
